Transform: 'AWS::Serverless-2016-10-31'
Resources:
    usersFunction:
        # This resource creates a Lambda function.
        Type: 'AWS::Serverless::Function'
        Properties:
            # This function uses the Nodejs v8.10 runtime.
            Runtime: nodejs12.x
            # This is the Lambda function's handler.
            Handler: app.entriesHandler
            # The location of the Lambda function code.
            CodeUri: ./src
            # Event sources to attach to this function. In this case, we are attaching
            # multiple API Gateway endpoints to the Lambda function. The function is
            # called when a HTTP request is made to the API Gateway endpoint.
            Events:
                lambdaGetAllEntries:
                    Type: Api
                    Properties:
                        Path: /
                        Method: GET
                lambdaGetEntry:
                    Type: Api
                    Properties:
                        Path: /{entryid}
                        Method: GET
                lambdaAddEntry:
                    Type: Api
                    Properties:
                        Path: /
                        Method: POST
                lambdaUpdateEntry:
                    Type: Api
                    Properties:
                        Path: /{entryid}
                        Method: PUT
                lambdaDeleteEntry:
                    Type: Api
                    Properties:
                        Path: /{entryid}
                        Method: DELETE
                lambdaAddComment:
                    Type: Api
                    Properties:
                        Path: /{entryid}/comments
                        Method: POST
                lambdaDeleteComment:
                    Type: Api
                    Properties:
                        Path: /{entryid}/comments/{commentid}
                        Method: DELETE
            Policies:
                # Policies to allow the execution of the indicated actions to the table described in Resource
                -   Version: '2020-5-4'
                    Statement: 
                        -   Effect: Allow
                            Action:
                                -   'dynamodb:Scan'
                                -   'dynamodb:DeleteItem'
                                -   'dynamodb:GetItem'
                                -   'dynamodb:PutItem'
                                -   'dynamodb:UpdateItem'
                            Resource:
                                'Fn::Join':
                                    -   ''
                                    -   -   'arn:aws:dynamodb:'
                                        -   Ref: 'AWS::Region'
                                        -   ':'
                                        -   Ref: 'AWS::AccountId'
                                        -   ':table/entries'
    
    entriesTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            TableName: entries
            AttributeDefinitions:
                -   AttributeName: entryid
                    AttributeType: S
            KeySchema:
                -   AttributeName: entryid
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PublicApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/api/entries/"